const bcrypt = require("bcryptjs");

const password = "123456";
const hashedPassword = bcrypt.hashSync(password, 12);

const {
    sequelize,
    Chat,
    Event,
    EventCategory,
    EventReview,
    JoinEventUser,
    QuickMessage,
    Transection,
    User,
    UserType,
} = require("../models");

sequelize
    .sync({ force: true })
    .then(() => {
        return UserType.bulkCreate([
            { id: 1, type: "Newbie" },
            { id: 2, type: "Explorer" },
            { id: 3, type: "UserGold" },
            { id: 4, type: "SupperUser" },
        ]);
    })

    .then(() => {
        return EventCategory.bulkCreate([
            { id: 1, name: "Bar" },
            { id: 2, name: "Sport" },
            { id: 3, name: "Resterant" },
            { id: 4, name: "Cafe" },
            { id: 5, name: "LifeStyle" },
        ]);
    })

    .then(() => {
        return User.bulkCreate([
            {
                id: 1,
                userName: "johndoe123",
                firstName: "John",
                lastName: "Doe",
                email: "johndoe123@example.com",
                password: hashedPassword,
                gender: "Male",
                bdate: "1990-07-15",
                image: "https://img.freepik.com/premium-vector/young-smiling-man-avatar-man-with-brown-beard-mustache-hair-wearing-yellow-sweater-sweatshirt-3d-vector-people-character-illustration-cartoon-minimal-style_365941-860.jpg",
                coin: 1000,
                aboutMe:
                    "I'm John Doe. I love playing badminton and hiking in my spare time.",
                status: true,
                isAdmin: false,
                userTypeId: 3,
            },
            {
                id: 2,
                userName: "janedoe456",
                firstName: "Jane",
                lastName: "Doe",
                email: "janedoe456@example.com",
                password: hashedPassword,
                gender: "Female",
                bdate: "1992-06-20",
                image: "https://img.freepik.com/premium-vector/young-smiling-african-man-avatar-3d-vector-people-character-illustration-cartoon-minimal-style_365941-883.jpg?w=2000",
                coin: 1200,
                aboutMe:
                    "Hi, I'm Jane Doe. I enjoy badminton and reading novels.",
                status: true,
                isAdmin: false,
                userTypeId: 1,
            },
            {
                id: 3,
                userName: "robertsmith789",
                firstName: "Robert",
                lastName: "Smith",
                email: "robertsmith789@example.com",
                password: hashedPassword,
                gender: "Male",
                bdate: "1985-10-30",
                image: "https://img.freepik.com/vecteurs-premium/diversite-vectorielle-3d-conception-icone-avatar-jeune-homme_624031-151.jpg?w=2000",
                coin: 1500,
                aboutMe:
                    "Hello, I'm Robert Smith. In my free time, I like to play badminton and write poetry.",
                status: true,
                isAdmin: true,
                userTypeId: 2,
            },
            {
                id: 4,
                userName: "emilyjohnson1011",
                firstName: "Emily",
                lastName: "Johnson",
                email: "emilyjohnson1011@example.com",
                password: hashedPassword,
                gender: "Female",
                bdate: "1993-04-12",
                image: "https://img.freepik.com/premium-vector/happy-young-woman-watching-into-rounded-frame-isolated-white-illustration-render-style_365941-118.jpg",
                coin: 800,
                aboutMe:
                    "I'm Emily Johnson. I'm a badminton enthusiast and love to travel.",
                status: true,
                isAdmin: false,
                userTypeId: 1,
            },
            {
                id: 5,
                userName: "michaeltaylor1213",
                firstName: "Michael",
                lastName: "Taylor",
                email: "michaeltaylor1213@example.com",
                password: hashedPassword,
                gender: "Male",
                bdate: "1989-01-25",
                image: "https://media.istockphoto.com/id/1389823037/vector/young-smiling-woman-mia-avatar-3d-vector-people-character-illustration-cartoon-minimal-style.jpg?s=612x612&w=0&k=20&c=ciwsDqBIy3mcTxhWN4I1S-kKSTvjoN1einMrQawNZDQ=",
                coin: 900,
                aboutMe:
                    "Hi, I'm Michael Taylor. I love playing badminton and watching movies.",
                status: true,
                isAdmin: false,
                userTypeId: 1,
            },
        ]);
    })

    .then(() => {
        return Event.bulkCreate([
            {
                id: 1,
                title: "Smash It Up! Community Badminton Event",
                description:
                    "Are you ready for a fun, engaging, and healthful event? Join us for our Community Badminton Event, titled Smash It Up!. This is a perfect opportunity to show off your badminton skills, meet new people, and get a great workout.",
                placeProvince: "Bangkok",
                placeName: "Mintower",
                placeCountry: "Thailand",
                dateStart: "2023-01-19 03:14:07",
                dateEnd: "2023-01-20 03:14:07",
                capacity: 10,
                image1: "https://images.unsplash.com/photo-1617696618050-b0fef0c666af?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image2: "https://images.unsplash.com/photo-1626326880051-9320471299c0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image3: "https://images.unsplash.com/photo-1633313236093-beebdd1a5e80?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1079&q=80",
                userId: 1,
                isBoost: 0,
                eventCategoryId: 2,
                latitude: 13.725,
                longitude: 100.352,
            },
            {
                id: 2,
                title: "Friday Night Bar Quiz",
                description:
                    "Join us for a fun-filled Friday night bar quiz! Gather your friends, test your knowledge, and enjoy some delicious drinks. Compete for prizes and bragging rights as the trivia champion of the night!",
                placeProvince: "Bangkok",
                placeName: "The Quiz Bar",
                placeCountry: "Thailand",
                dateStart: "2023-02-10 20:00:00",
                dateEnd: "2023-02-10 22:00:00",
                capacity: 30,
                image1: "https://images.unsplash.com/photo-1575444758702-4a6b9222336e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image2: "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1429&q=80",
                image3: "https://plus.unsplash.com/premium_photo-1674374441957-39c93764b3e5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                userId: 2,
                isBoost: 0,
                eventCategoryId: 1,
                latitude: 13.756,
                longitude: 100.501,
            },
            {
                id: 3,
                title: "Sports Marathon Challenge",
                description:
                    "Calling all sports enthusiasts! Join us for an exciting sports marathon challenge. Participate in various sports activities like basketball, football, and volleyball. Show off your skills and compete for the ultimate champion title!",
                placeProvince: "Bangkok",
                placeName: "City Sports Complex",
                placeCountry: "Thailand",
                dateStart: "2023-03-05 09:00:00",
                dateEnd: "2023-03-05 18:00:00",
                capacity: 50,
                image1: "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1474&q=80",
                image2: "https://images.unsplash.com/photo-1581889470536-467bdbe30cd0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2464&q=80",
                image3: "https://images.unsplash.com/photo-1502904550040-7534597429ae?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1700&q=80",
                userId: 3,
                isBoost: 0,
                eventCategoryId: 2,
                latitude: 13.719,
                longitude: 100.548,
            },
            {
                id: 4,
                title: "Savor the Flavors Food Festival",
                description:
                    "Experience a gastronomic delight at the Savor the Flavors Food Festival. Indulge in a wide variety of cuisines, try unique dishes, and enjoy live music performances. Treat your taste buds to a memorable culinary experience!",
                placeProvince: "Bangkok",
                placeName: "Food Paradise Park",
                placeCountry: "Thailand",
                dateStart: "2023-04-20 12:00:00",
                dateEnd: "2023-04-22 22:00:00",
                capacity: 100,
                image1: "https://images.unsplash.com/photo-1570441643218-33b4b88572bf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1072&q=80",
                image1: "https://images.unsplash.com/photo-1604071489531-21b6358751cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image1: "https://images.unsplash.com/photo-1524584830732-b69165ddba9a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1433&q=80",
                userId: 4,
                isBoost: 0,
                eventCategoryId: 3,
                latitude: 13.755,
                longitude: 100.534,
            },
            {
                id: 5,
                title: "Café Art Exhibition",
                description:
                    "Step into the world of art at our Café Art Exhibition. Enjoy a cup of coffee while appreciating beautiful artworks from local artists. Immerse yourself in creativity and engage in insightful conversations about art.",
                placeProvince: "Bangkok",
                placeName: "Artful Brew Café",
                placeCountry: "Thailand",
                dateStart: "2023-06-15 10:00:00",
                dateEnd: "2023-06-15 18:00:00",
                capacity: 20,
                image1: "https://images.unsplash.com/photo-1600903781679-7ea3cbc564c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image2: "https://images.unsplash.com/photo-1566954979172-eaba308acdf0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1631&q=80",
                image3: "https://images.unsplash.com/photo-1580687581604-0e57ffe41812?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                userId: 5,
                isBoost: 0,
                eventCategoryId: 4,
                latitude: 13.751,
                longitude: 100.492,
            },
            {
                id: 6,
                title: "Sunday Funday Sports Day",
                description:
                    "Join us for a Sunday Funday Sports Day! Bring your friends and enjoy a day filled with various sports activities like frisbee, badminton, and soccer. Get active, have fun, and make lasting memories!",
                placeProvince: "Bangkok",
                placeName: "Sunshine Sports Club",
                placeCountry: "Thailand",
                dateStart: "2023-07-02 10:00:00",
                dateEnd: "2023-07-02 16:00:00",
                capacity: 30,
                image1: "https://images.unsplash.com/photo-1598785981370-6190e9bb79b1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image2: "https://images.unsplash.com/photo-1529138682105-e9d66b96f313?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image3: "https://images.unsplash.com/photo-1528200465331-fd30f8ee3afc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1075&q=80",
                userId: 1,
                isBoost: 0,
                eventCategoryId: 2,
                latitude: 13.736,
                longitude: 100.517,
            },
            {
                id: 7,
                title: "Restaurant Cuisine Showcase",
                description:
                    "Embark on a culinary journey at our Restaurant Cuisine Showcase. Discover the flavors of international cuisines as talented chefs prepare mouthwatering dishes right before your eyes. Experience a world of tastes in one place!",
                placeProvince: "Bangkok",
                placeName: "Taste Boulevard",
                placeCountry: "Thailand",
                dateStart: "2023-08-10 18:30:00",
                dateEnd: "2023-08-10 22:00:00",
                capacity: 25,
                image1: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image2: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image3: "https://images.unsplash.com/photo-1605200716925-7bc00504842f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                userId: 2,
                isBoost: 0,
                eventCategoryId: 3,
                latitude: 13.748,
                longitude: 100.517,
            },
            {
                id: 8,
                title: "Coffee Tasting Workshop",
                description:
                    "Delve into the world of coffee with our Coffee Tasting Workshop. Learn about different coffee beans, brewing techniques, and flavor profiles. Enhance your coffee knowledge and refine your taste for this beloved beverage.",
                placeProvince: "Bangkok",
                placeName: "Java Junction",
                placeCountry: "Thailand",
                dateStart: "2023-09-16 14:00:00",
                dateEnd: "2023-09-16 16:00:00",
                capacity: 15,
                image1: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image2: "https://images.unsplash.com/photo-1493857671505-72967e2e2760?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image3: "https://images.unsplash.com/photo-1505275350441-83dcda8eeef5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
                userId: 4,
                isBoost: 1,
                eventCategoryId: 4,
                latitude: 13.722,
                longitude: 100.57,
            },
            {
                id: 9,
                title: "Yoga Retreat: Serenity in the City",
                description:
                    "Escape the hustle and bustle of the city and find serenity in our Yoga Retreat. Relax your mind, rejuvenate your body, and restore your inner balance through yoga sessions, meditation, and holistic wellness practices.",
                placeProvince: "Bangkok",
                placeName: "Urban Oasis Yoga Studio",
                placeCountry: "Thailand",
                dateStart: "2023-10-20 09:00:00",
                dateEnd: "2023-10-22 17:00:00",
                capacity: 20,
                image1: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image2: "https://images.unsplash.com/photo-1588783344727-f67e17b45dfc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image3: "https://images.unsplash.com/photo-1584937047511-6cb661f59687?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                userId: 5,
                isBoost: 0,
                eventCategoryId: 5,
                latitude: 13.743,
                longitude: 100.552,
            },
            {
                id: 10,
                title: "Friday Night Live Music",
                description:
                    "Kickstart your weekend with Friday Night Live Music! Enjoy a variety of musical performances, from acoustic sessions to energetic bands. Savor delicious food and drinks while grooving to the rhythm.",
                placeProvince: "Bangkok",
                placeName: "Rhythm & Brews",
                placeCountry: "Thailand",
                dateStart: "2023-11-03 19:00:00",
                dateEnd: "2023-11-03 23:00:00",
                capacity: 30,
                image1: "https://images.unsplash.com/photo-1597158520886-43e23f1acb1e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image2: "https://images.unsplash.com/photo-1483069125343-4ef290c07840?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1471&q=80",
                image3: "https://images.unsplash.com/photo-1507874457470-272b3c8d8ee2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                userId: 1,
                isBoost: 0,
                eventCategoryId: 1,
                latitude: 13.758,
                longitude: 100.567,
            },
            {
                id: 11,
                title: "Outdoor Adventure Day",
                description:
                    "Join us for an Outdoor Adventure Day filled with thrilling activities like rock climbing, zip-lining, and trekking. Challenge yourself, conquer your fears, and create unforgettable memories in the great outdoors.",
                placeProvince: "Bangkok",
                placeName: "Adventure Peak",
                placeCountry: "Thailand",
                dateStart: "2023-12-09 08:00:00",
                dateEnd: "2023-12-09 16:00:00",
                capacity: 15,
                image1: "https://images.unsplash.com/photo-1586627161720-ee2849303aee?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image2: "hhttps://images.unsplash.com/photo-1467139701929-18c0d27a7516?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image3: "https://images.unsplash.com/photo-1577434150790-3bfe143fe4f2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                userId: 3,
                isBoost: 1,
                eventCategoryId: 5,
                latitude: 13.714,
                longitude: 100.535,
            },
            {
                id: 12,
                title: "Fashion and Style Workshop",
                description:
                    "Explore the world of fashion and style at our interactive workshop. Learn about the latest trends, fashion tips, and personal styling techniques from industry experts. Unleash your creativity and define your unique style!",
                placeProvince: "Bangkok",
                placeName: "Style Avenue",
                placeCountry: "Thailand",
                dateStart: "2023-12-27 14:30:00",
                dateEnd: "2023-12-27 17:00:00",
                capacity: 20,
                image1: "https://images.unsplash.com/photo-1445205170230-053b83016050?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1471&q=80",
                image2: "https://images.unsplash.com/photo-1462392246754-28dfa2df8e6b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                image3: "https://images.unsplash.com/photo-1525562723836-dca67a71d5f1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
                userId: 1,
                isBoost: 0,
                eventCategoryId: 5,
                latitude: 13.75,
                longitude: 100.539,
            },
        ]);
    })
    .then(() => {
        return JoinEventUser.bulkCreate([
            { id: 1, userId: 1, eventId: 8 },
            { id: 2, userId: 2, eventId: 6 },
            { id: 3, userId: 3, eventId: 3 },
            { id: 4, userId: 4, eventId: 10 },
            { id: 5, userId: 5, eventId: 5 },
            { id: 6, userId: 2, eventId: 2 },
            { id: 7, userId: 3, eventId: 4 },
            { id: 8, userId: 4, eventId: 12 },
            { id: 9, userId: 5, eventId: 9 },
            { id: 10, userId: 1, eventId: 1 },
            { id: 11, userId: 3, eventId: 11 },
            { id: 12, userId: 5, eventId: 7 },
            { id: 13, userId: 1, eventId: 12 },
            { id: 14, userId: 2, eventId: 4 },
            { id: 15, userId: 3, eventId: 6 },
            { id: 16, userId: 4, eventId: 3 },
            { id: 17, userId: 2, eventId: 9 },
            { id: 18, userId: 4, eventId: 1 },
            { id: 19, userId: 5, eventId: 8 },
            { id: 20, userId: 1, eventId: 6 },
            { id: 21, userId: 3, eventId: 10 },
            { id: 22, userId: 2, eventId: 3 },
            { id: 23, userId: 3, eventId: 9 },
            { id: 24, userId: 4, eventId: 6 },
            { id: 25, userId: 5, eventId: 1 },
            { id: 26, userId: 1, eventId: 10 },
            { id: 27, userId: 4, eventId: 8 },
            { id: 28, userId: 2, eventId: 12 },
            { id: 29, userId: 3, eventId: 5 },
            { id: 30, userId: 4, eventId: 2 },
            { id: 31, userId: 5, eventId: 6 },
            { id: 32, userId: 1, eventId: 9 },
            { id: 33, userId: 2, eventId: 1 },
            { id: 34, userId: 4, eventId: 11 },
            { id: 35, userId: 5, eventId: 4 },
            { id: 36, userId: 1, eventId: 5 },
            { id: 37, userId: 2, eventId: 7 },
            { id: 38, userId: 5, eventId: 2 },
            { id: 39, userId: 4, eventId: 4 },
            { id: 40, userId: 4, eventId: 1 },
        ]);
    })

    .then(() => {
        return QuickMessage.bulkCreate([
            { id: 1, message: "OK !! I will go together" },
            { id: 2, message: "I am interested" },
            { id: 3, message: "How much for go event" },
        ]);
    })

    .then(() => {
        return Chat.bulkCreate([
            {
                id: 1,
                message: "Hello, is anyone up for badminton this weekend?",
                userId: 1,
                eventId: 8,
            },
            {
                id: 2,
                message: "Looking forward to the event! Who else is joining?",
                userId: 1,
                eventId: 10,
            },
            {
                id: 3,
                message: "Any suggestions for the meeting point?",
                userId: 3,
                eventId: 11,
            },
            {
                id: 4,
                message: "I'm excited about the upcoming event. Can't wait!",
                userId: 4,
                eventId: 8,
            },
            {
                id: 5,
                message: "Is anyone bringing their own equipment?",
                userId: 2,
                eventId: 9,
            },
            {
                id: 6,
                message: "Let's have a friendly match during the event!",
                userId: 5,
                eventId: 5,
            },
            {
                id: 7,
                message: "Looking forward to meeting new people at the event.",
                userId: 1,
                eventId: 7,
            },
            {
                id: 8,
                message: "Does anyone need a doubles partner?",
                userId: 3,
                eventId: 4,
            },
            {
                id: 9,
                message: "Can't wait to play badminton again!",
                userId: 2,
                eventId: 12,
            },
            {
                id: 10,
                message:
                    "What's the skill level of participants in this event?",
                userId: 5,
                eventId: 9,
            },
            {
                id: 11,
                message: "Looking forward to a great game!",
                userId: 4,
                eventId: 6,
            },
            {
                id: 12,
                message: "Is there a registration fee for this event?",
                userId: 1,
                eventId: 1,
            },
            {
                id: 13,
                message: "Any recommendations for nearby cafes?",
                userId: 3,
                eventId: 11,
            },
            {
                id: 14,
                message: "I hope the weather is good for the event!",
                userId: 5,
                eventId: 4,
            },
            {
                id: 15,
                message:
                    "Looking forward to meeting fellow badminton enthusiasts.",
                userId: 2,
                eventId: 7,
            },
            {
                id: 16,
                message: "Excited to see everyone's skills on the court!",
                userId: 1,
                eventId: 10,
            },
            {
                id: 17,
                message: "Is there an age limit for the event?",
                userId: 4,
                eventId: 8,
            },
            {
                id: 18,
                message: "Looking forward to a fun-filled day of badminton!",
                userId: 5,
                eventId: 2,
            },
            {
                id: 19,
                message: "Who's bringing the shuttlecocks?",
                userId: 2,
                eventId: 12,
            },
            {
                id: 20,
                message:
                    "Excited to compete with skilled players at the event!",
                userId: 1,
                eventId: 8,
            },
        ]);
    })

    .then(() => process.exit(0))
    .catch((err) => console.log(err.message));
